# Generated by Django 6.0.5 on 2026-05-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
    ]
