# Generated by Django 6.0.5 on 2026-05-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0002_alter_company_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissionrecord",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
    ]
