# Generated by Django 6.0.5 on 2026-05-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0003_alter_emissionrecord_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emissionrecord",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="emissionrecord",
            name="date",
        ),
        migrations.RemoveField(
            model_name="emissionrecord",
            name="locked",
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="from_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="to_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="travel_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="travel_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="normalized_unit",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="scope",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="unit",
            field=models.CharField(max_length=20),
        ),
    ]
