# Generated by Django 6.0.5 on 2026-05-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0004_remove_emissionrecord_approved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emissionrecord",
            name="company",
        ),
        migrations.RemoveField(
            model_name="datasource",
            name="company",
        ),
        migrations.RemoveField(
            model_name="emissionrecord",
            name="source",
        ),
        migrations.RemoveField(
            model_name="emissionrecord",
            name="from_location",
        ),
        migrations.RemoveField(
            model_name="emissionrecord",
            name="normalized_unit",
        ),
        migrations.RemoveField(
            model_name="emissionrecord",
            name="to_location",
        ),
        migrations.RemoveField(
            model_name="emissionrecord",
            name="travel_date",
        ),
        migrations.RemoveField(
            model_name="emissionrecord",
            name="travel_type",
        ),
        migrations.RemoveField(
            model_name="emissionrecord",
            name="unit",
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="company_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="source_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="travel_from",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="travel_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="new_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="old_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="normalized_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="scope",
            field=models.CharField(
                choices=[
                    ("SCOPE_1", "Scope 1"),
                    ("SCOPE_2", "Scope 2"),
                    ("SCOPE_3", "Scope 3"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("LOCKED", "Locked"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="DataSource",
        ),
    ]
