# Generated by Django 6.0.5 on 2026-05-25 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0005_remove_emissionrecord_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionrecord",
            name="travel_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="travel_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("SAP", "SAP"), ("UTILITY", "Utility"), ("TRAVEL", "Travel")],
                max_length=50,
                null=True,
            ),
        ),
    ]
