# Generated by Django 6.0.5 on 2026-05-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0006_emissionrecord_travel_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
