# Generated by Django 6.0.5 on 2026-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0007_emissionrecord_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("LOCKED", "Locked"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
