# Generated by Django 6.0.5 on 2026-05-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0008_alter_emissionrecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionrecord",
            name="failed_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
