# Generated by Django 6.0.5 on 2026-05-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0010_company_remove_emissionrecord_company_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emissionrecord",
            name="distance_km",
        ),
    ]
