# Generated by Django 6.0.5 on 2026-05-26 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0011_remove_emissionrecord_distance_km"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(
                related_name="companies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
