# Generated by Django 6.0.5 on 2026-05-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0012_company_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissionrecord",
            name="raw_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
